build-ubuntu:
  image: i386/ubuntu:rolling

  variables:
    DEBIAN_FRONTEND: noninteractive

  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends check gcc libavahi-glib-dev libgdk-pixbuf2.0-dev libgee-0.8-dev libglib2.0-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libsoup2.4-dev pkg-config

  script:
    - ./configure
    - make
    - make check
