build-ubuntu:
  image: i386/ubuntu:eoan

  variables:
    DEBIAN_FRONTEND: noninteractive

  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends autoconf automake avahi-daemon check gcc gtk-doc-tools libavahi-client-dev libavahi-compat-libdnssd-dev libavahi-glib-dev libgdk-pixbuf2.0-dev libgee-0.8-dev libglib2.0-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libsoup2.4-dev libtool pkg-config

  script:
    - ./autogen.sh --with-mdns=avahi --disable-tests --enable-more-warnings
    - make CFLAGS="-Wall -Wextra -Werror"
    - make clean
    - ./configure --with-mdns=dns_sd --disable-tests --enable-more-warnings
    - make CFLAGS="-Wall -Wextra -Werror"
    - make clean

build-alpine:
  image: alpine:arm32v7/latest

  before_script:
    - apk update
    - apk add --no-cache autoconf automake avahi-compat-libdns_sd avahi-glib avahi-dev check gcc gtk-doc gdk-pixbuf-dev libgee-dev glib-dev gst-plugins-base-dev gtk+3.0-dev libsoup-dev libtool pkgconf

  script:
    - ./autogen.sh --with-mdns=avahi --disable-tests --enable-more-warnings
    - make CFLAGS="-Wall -Wextra -Werror"
    - make clean
    - ./configure --with-mdns=dns_sd --disable-tests --enable-more-warnings
    - make CFLAGS="-Wall -Wextra -Werror"
    - make clean
