build-ubuntu:
  image: i386/ubuntu:eoan

  variables:
    DEBIAN_FRONTEND: noninteractive

  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends autoconf automake avahi-daemon check gcc gtk-doc-tools libavahi-client-dev libavahi-compat-libdnssd-dev libavahi-glib-dev libgdk-pixbuf2.0-dev libgee-0.8-dev libglib2.0-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libsoup2.4-dev libtool pkg-config

  script:
    - ./autogen.sh --with-mdns=avahi --disable-tests --enable-more-warnings
    - make CFLAGS="-Wall -Wextra -Werror"
    - make clean
    - ./configure --with-mdns=dns_sd --disable-tests --enable-more-warnings
    - make CFLAGS="-Wall -Wextra -Werror"
    - make clean

build-fedora:
  image: fedora:latest

  before_script:
    - dnf -y update
    - dnf -y install autoconf automake check-devel gcc gtk-doc avahi-glib-devel avahi-compat-libdns_sd-devel gdk-pixbuf2-devel libgee-devel glib2-devel gstreamer1-plugins-base-devel gtk3-devel libsoup-devel libtool pkgconf-pkg-config rpm-build

  script:
    - ./autogen.sh --with-mdns=avahi --disable-tests --enable-more-warnings
    - make CFLAGS="-Wall -Wextra -Werror"
    - make dist
    - mkdir -p ~/rpmbuild/SOURCES
    - cp libdmapsharing-*.*.*.tar.gz ~/rpmbuild/SOURCES
    - rpmbuild -ba distro/libdmapsharing4.spec

  artifacts:
    paths:
       - ~/rpmbuild/RPMS/
       - ~/rpmbuild/SRPMS/
    expire_in: 1 week
