#!/usr/bin/env python3

import gi
import sys

gi.require_version('DMAP', '3.2')
gi.require_version('DAAP', '3.2')

from gi.repository import GObject
from gi.repository import GLib
from gi.repository import DMAP
from gi.repository import DAAP

import testpython

class TestDMAPServer(GObject.GObject):
    def __init__(self):
        super(TestDMAPServer, self).__init__()

        name = 'Python libdmapsharing test'

        self.container_record = testpython.PyDMAPContainerRecord()
        self.container_db     = testpython.PyDMAPContainerDb()
        self.factory          = testpython.PyDAAPRecordFactory()
        self.db               = testpython.PyDMAPDb()

        record = testpython.PyDAAPRecord()

        record.set_property('title', 'test-title')
        record.set_property('songalbum', 'test-album')
        record.set_property('sort-album', 'test-sort-album')
        record.set_property('songartist', 'test-artist')
        record.set_property('sort-artist', 'test-sort-artist')
        record.set_property('songgenre', 'test-genre')
        record.set_property('format', 'test-format')
        record.set_property('rating', 0)
        record.set_property('filesize', 1)
        record.set_property('duration', 2)
        record.set_property('track', 3)
        record.set_property('year', 4)
        record.set_property('firstseen', 5)
        record.set_property('mtime', 6)
        record.set_property('disc', 7)
        record.set_property('bitrate', 8)
        record.set_property('has-video', False)
        record.set_property('mediakind', DMAP.MediaKind.MUSIC)

        self.db.add(record)

        self.share            = DAAP.Share.new(name, 'password', self.db, self.container_db, 'audio/mp3')

server = TestDMAPServer ()
GLib.MainLoop().run()
